CREATE OR REPLACE PACKAGE PBLHO.PKG_REGISTERED_USERS
AS

PROCEDURE P_Get_Registered_User(P_USERNAME IN VARCHAR2, O_USER_C OUT SYS_REFCURSOR);

END PKG_REGISTERED_USERS;
/


CREATE OR REPLACE PACKAGE BODY PBLHO.PKG_REGISTERED_USERS
AS

PROCEDURE P_Get_Registered_User(P_USERNAME IN VARCHAR2, O_USER_C OUT SYS_REFCURSOR)
AS
v_msg VARCHAR2(255);
BEGIN

    OPEN O_USER_C FOR
    SELECT USERNAME,PASSWORD from PBLHO.RegisteredUsers WHERE USERNAME = P_USERNAME;
  
    EXCEPTION
    WHEN OTHERS THEN
    v_msg := SQLERRM; 
    dbms_output.put_line('Error Get Data:'||v_msg);
    RAISE;

END P_Get_Registered_User;

END PKG_REGISTERED_USERS;
/

set serveroutput on;  
declare O_PASSWORD varchar2(150);
O_USERNAME varchar2(150);
BEGIN
  PBLHO.PKG_REGISTERED_USERS.P_Get_Registered_User('sabbir',O_USERNAME,O_PASSWORD);
  dbms_output.put_line(O_USERNAME);  
  dbms_output.put_line(O_PASSWORD); 
END;
