CREATE TABLE PBLHO.RegisteredUsers
(
    USERID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    DISPLAYNAME  VARCHAR2(60 BYTE) NOT NULL,
    USERNAME     VARCHAR2(50 BYTE) NOT NULL,
    PASSWORD     VARCHAR2(150 BYTE) NOT NULL,
    WORKSTATION  VARCHAR2(15 BYTE)  DEFAULT SYS_CONTEXT('USERENV','IP_ADDRESS') NOT NULL,
    CREATEDDATE  DATE DEFAULT SYSDATE NOT NULL,
    CREATEDBY    VARCHAR2(50 BYTE) DEFAULT USER NOT NULL,
    PRIMARY KEY(USERNAME)
)


CREATE TABLE PBLHO.TodoItem
(
    ITEMID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    ITEMNAME  VARCHAR2(100 BYTE) NOT NULL,
    ISCOMPLETE  CHAR(1) DEFAULT 'N' NOT NULL,
    WORKSTATION  VARCHAR2(15 BYTE)  DEFAULT SYS_CONTEXT('USERENV','IP_ADDRESS') NOT NULL,
    CREATEDDATE  DATE DEFAULT SYSDATE NOT NULL,
    CREATEDBY    VARCHAR2(50 BYTE) DEFAULT USER NOT NULL,
    PRIMARY KEY(ITEMID)
)

SELECT ITEMID,ITEMNAME,ISCOMPLETE FROM PBLHO.TodoItem ORDER BY ITEMID;

DELETE  FROM PBLHO.TodoItem A WHERE A.ITEMID = 4; 

--drop table PBLHO.RegisteredUsers



